# Static persistent volume manifest
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph-external
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph-external
    volumeAttributes:
      clusterID: rook-ceph-external
      fsName: cephfs
      subvolumeName: media
      subvolumePath: /volumes/data/media/8fab24e4-e6c1-4789-9643-a9fc5df90b77
    volumeHandle: media-plex
  # reclaim policy is to retain, as it is a pre-provisioned volume and would require a PV delete
  # to remove the same from the kubernetes system
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  # volumeName tying this PCV to a specific PV
  volumeName: media
