apiVersion: v2
name: zem-velero
description: A Helm chart for Kubernetes (opinionated Velero wrapper)

type: application
version: 0.1.0
appVersion: "1.90.8"

dependencies:
  - name: velero
    version: 11.1.1
    repository: https://vmware-tanzu.github.io/helm-charts
