apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backups-zem-external-{{.Values.env }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: zem-external-{{ .Values.env }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-backups
    helm:
      valuesObject:
        ociVault:
          vaultOcid: {{ .Values.ociVault.vaultOcid | quote }}
          compartmentOcid: {{ .Values.ociVault.compartmentOcid | quote }}
          region: {{ .Values.ociVault.region | quote }}
          tenancyOcid: {{ .Values.ociVault.tenancyOcid | quote }}
          userOcid: {{ .Values.backups.ociUserOcid | quote }}
          credentialSecretName: {{ .Values.backups.ociCredentialSecret | quote }}
        b2:
          prefix: {{ .Values.cluster }}/zem-external-{{ .Values.env }}
          vaultSecretName: {{ .Values.cluster }}-zem-external-{{ .Values.env }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: zem-external-{{ .Values.env }}
