apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
  name: kubernetes-external
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
  sessionAffinity: None
  type: LoadBalancer
