{{ if .Values.features.alloy.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: infra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-alloy
    helm:
      releaseName: alloy
      valuesObject:
        ingress:
          tls:
            - hosts:
                - {{ .Values.features.alloy.hostname | quote }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
{{ end }}