{{ if .Values.features.reloader.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: infra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.1.1
    helm:
      releaseName: alloy
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: tailscale
          faroPort: 12345
          hosts: []
          tls:
            - hosts:
                - alloy
        alloy:
          configmap:
            content: |-
              // Write your Alloy config here:
              logging {
                level = "info"
                format = "logfmt"
              }
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
{{ end }}