{{ if .Values.features.externalsecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-external-secrets
  namespace: argocd
spec:
  description: External Secrets
  destinations:
    - namespace: "external-secrets"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://github.com/danfoster/zem-gitops"
{{ end }}