{{ if .Values.features.certmanager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infra-cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-cert-manager-configs
    helm:
      releaseName: cert-manager-configs
      valuesObject:
      {{- toYaml .Values.features.certmanager | nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: externaldns
{{ end }}