{{ if .Values.features.certmanager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Cert Manager
  destinations:
    - namespace: "cert-manager"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://github.com/danfoster/zem-gitops"
{{ end }}