{{ if .Values.features.externaldns.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-externaldns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: ExternalDNS
  destinations:
    - namespace: "externaldns"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://github.com/danfoster/zem-gitops"
{{ end }}