{{ if .Values.features.externalsecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: infra-external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-external-secrets
    helm:
      valuesObject:
      {{- toYaml .Values.features.externalsecrets | nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
{{ end }}