{{ if .Values.features.ingressnginx.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: infra-ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.3
    helm:
      releaseName: ingress-nginx
      valuesObject:
      {{- toYaml .Values.features.ingressnginx | nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
{{ end }}