{{ if .Values.features.kube_state_metrics.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: infra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-kube-state-metrics
    helm:
      releaseName: kube-state-metrics
      valuesObject:
      {{- toYaml .Values.features.kube_state_metrics | nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
{{ end }}