{{ if .Values.features.metallb.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-configs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-metallb-configs
    helm:
      releaseName: metallb-configs
      valuesObject:
        {{- toYaml .Values.features.metallb | nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb
{{ end }}