{{ if .Values.features.openebs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-openebs
    helm:
      releaseName: openebs
      valuesObject:
      {{- toYaml .Values.features.openebs | nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
{{ end }}