{{ if .Values.features.openebs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-openebs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: OpenEBS
  destinations:
    - namespace: "openebs"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://openebs.github.io/charts"
    - "https://github.com/danfoster/zem-gitops"
{{ end }}