{{ if .Values.features.openebs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: infra-openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-openebs
    helm:
      releaseName: openebs
      valuesObject:
        storageclasses:
          zfs:
            enabled: {{ .Values.features.openebs.storageclasses.zfs.enabled | quote }}
            poolname: {{ .Values.features.openebs.storageclasses.zfs.poolname | quote }}
            default: {{ .Values.features.openebs.storageclasses.zfs.default | quote }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
{{ end }}