{{ if .Values.features.reloader.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-reloader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Reloader
  destinations:
    - namespace: "reloader"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://stakater.github.io/stakater-charts"
{{ end }}