{{ if .Values.features.argocd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-tailscale
  namespace: tailscale
spec:
  description: Tailscale
  destinations:
    - namespace: "argocd"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://github.com/danfoster/zem-gitops"
{{ end }}