{{ if .Values.features.alloy.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd
spec:
  project: infra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-victoriametrics
    helm:
      releaseName: victoriametrics
      valuesObject:
        victoriametrics:
          vmagent:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
{{ end }}