{{ if .Values.features.vmoperator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmoperator
  namespace: argocd
spec:
  project: infra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-vmoperator
    helm:
      releaseName: vmoperator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  ignoreDifferences:
    - kind: Service
      jsonPointers:
        - /spec/externalName
{{ end }}