{{ if .Values.features.zfs_exporter.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zfs-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://charts.enix.io
    chart: zfs-exporter
    targetRevision: 2.1.0
    helm:
      releaseName: zfs-exporter
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
{{ end }}