apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: media
    volumeAttributes:
      collection: default
      replication: "001"
      path: /media/
    readOnly: true
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  storageClassName: ""
  volumeName: media
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi