apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: static
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: static
      containers:
        - image: "nginx:1-alpine"
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            limits:
              cpu: '0.1'
              memory: 50Mi
            requests:
              ephemeral-storage: 4Gi
              cpu: '0.1'
              memory: 50Mi
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: static
      restartPolicy: Always
