apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        client_id: "{{ .Values.oauth.clientId }}"
        client_secret: "{{ `{{.client_secret}}` }}"
  data:
    - secretKey: client_secret
      remoteRef:
        key: "{{ .Values.oauth.clientSecretKey }}"
