apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omada-{{ .Values.env }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: networking-{{ .Values.env }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/networking/omada
    helm:
      releaseName: omada
      valuesObject:
      {{- toYaml .Values.omada | nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: networking-{{ .Values.env }}