apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking-prod
  namespace: argocd
spec:
  description: pce
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://github.com/danfoster/zem-gitops"
