apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-smartctl-exporter
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-smartctl-exporter
    app.kubernetes.io/name: prometheus-smartctl-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-smartctl-exporter
  revisionHistoryLimit: 10
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app.kubernetes.io/component: metrics
        app.kubernetes.io/part-of: prometheus-smartctl-exporter
        app.kubernetes.io/name: prometheus-smartctl-exporter
    spec:
      securityContext:
        runAsUser: 0 # Run as root user
        runAsGroup: 6 # Set primary GID to 6 (disk group)
        fsGroup: 6 # Set file system group for mounted volumes
      containers:
        - name: smartctl-exporter
          image: prometheuscommunity/smartctl-exporter:v0.14.0
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              add: ["SYS_RAWIO", "DAC_READ_SEARCH"]
          livenessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
              path: /
              port: 9633
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
              path: /
              port: 9633
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: host-dev
              mountPath: /dev
              mountPropagation: HostToContainer
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists

      volumes:
        - name: host-dev
          hostPath:
            path: /dev
