apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: smartctl-exporter
spec:
  endpoints:
    - port: metrics
      relabelConfigs:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: hostname
          action: replace
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-smartctl-exporter
