{{- if and .Values.rclone.enabled .Values.rclone.externalSecret.enabled }}
# Templated ExternalSecret manifest. Fill `spec.secretStoreRef` and `spec.data`
# via cluster-level overrides or by setting values under `rclone.externalSecret`.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.rclone.externalSecret.targetSecretName }}
  labels:
    app: {{ .Release.Name }}-rclone
spec:
  # The secret store reference must be provided by the cluster operator.
  # Example (fill in a valid SecretStore/ClusterSecretStore name):
  # secretStoreRef:
  #   name: my-secret-store
  #   kind: SecretStore
  # The `data` section should map keys from your secret store into the target k8s Secret.
  # Provide this mapping via values (see chart README or cluster overrides).
  # Below is intentionally left empty so clusters can safely supply the mapping.
  target:
    name: {{ .Values.rclone.configSecretName }}
  # Example placeholder (commented):
  # data:
  #   - secretKey: rclone.conf
  #     remoteRef:
  #       key: path/to/rclone.conf
{{- end }}
