apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-repo-credentials
  labels:
    app.kubernetes.io/name: velero
spec:
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    name: velero-repo-credentials
  data:
    - secretKey: repository-password
      remoteRef:
        key: velero-repo-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
