{{- if .Values.schedules.daily.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  labels:
    app.kubernetes.io/name: velero
spec:
  schedule: "{{ .Values.schedules.daily.schedule }}"
  template:
    ttl: "{{ .Values.schedules.daily.ttl }}"
    {{- if .Values.schedules.daily.includedNamespaces }}
    includedNamespaces:
      {{- toYaml .Values.schedules.daily.includedNamespaces | nindent 6 }}
    {{- end }}
    {{- if .Values.schedules.daily.excludedNamespaces }}
    excludedNamespaces:
      {{- toYaml .Values.schedules.daily.excludedNamespaces | nindent 6 }}
    {{- end }}
    storageLocation: b2-default
    defaultVolumesToFsBackup: {{ .Values.schedules.daily.defaultVolumesToFsBackup }}
{{- end }}
