apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  labels:
    app: samba
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      name: samba
      labels:
        app: samba
    spec:
      containers:
        - name: samba
          image: ghcr.io/servercontainers/samba:a3.22.1-s4.21.4-r4
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: "1"
              memory: 512Mi
          ports:
            - containerPort: 139
              protocol: TCP
            - containerPort: 445
              protocol: TCP
            - containerPort: 137
              protocol: UDP

          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /home/
              name: home

          envFrom:
            - secretRef:
                name: samba
            - configMapRef:
                name: samba

      volumes:
        - name: data
          hostPath:
            path: /data/
            type: Directory
        - name: home
          hostPath:
            path: /home/dan
            type: Directory
