apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: samba
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  data:
    - secretKey: ACCOUNT_dan
      remoteRef:
        key: "samba-dan"
