kind: Service
apiVersion: v1
metadata:
  name: samba
  annotations:
    tailscale.com/hostname: samba
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: samba
  ports:
    - protocol: TCP
      name: samba1
      port: 445
    - protocol: TCP
      name: samba2
      port: 139
    - protocol: UDP
      name: samba3
      port: 137
