apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: zem-infra
  # annotations:
    # "helm.sh/hook": post-install,post-upgrade
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          infra: "true"
    - namespaces:
        - zem-internal-prod
        - media-prod
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bw-auth-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-bootstrap-certificate
        key: ca.crt
        namespace: external-secrets
      organizationID: {{ .Values.bitwarden.organizationID }}
      projectID: {{ .Values.bitwarden.projectID }}