{{- if .Values.ociVault.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  conditions:
    {{- toYaml .Values.ociVault.conditions | nindent 4 }}
  provider:
    oracle:
      vault: {{ .Values.ociVault.vault | quote }}
      compartment: {{ .Values.ociVault.compartment | quote }}
      region: {{ .Values.ociVault.region | quote }}
      principalType: UserPrincipal
      auth:
        user: {{ .Values.ociVault.user | quote }}
        tenancy: {{ .Values.ociVault.tenancy | quote }}
        secretRef:
          privatekey:
            name: {{ .Values.ociVault.authSecret.name }}
            key: privateKey
            namespace: {{ .Values.ociVault.authSecret.namespace }}
          fingerprint:
            name: {{ .Values.ociVault.authSecret.name }}
            key: fingerprint
            namespace: {{ .Values.ociVault.authSecret.namespace }}
{{- end }}
