apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Values.restic.secretName }}"
spec:
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: k8up-restic-key
