apiVersion: v1
data:
  config.alloy: |-
    // Write your Alloy config here:
    logging {
        level = "info"
        format = "logfmt"
    }
    livedebugging {
      enabled = true
    }
    discovery.kubernetes "pods" {
        role = "pod"
    }
kind: ConfigMap
metadata:
  name: alloy-config
