apiVersion: v1
data:
  config.alloy: |-
    // Write your Alloy config here:
    logging {
        level = "info"
        format = "logfmt"
    }
    livedebugging {
      enabled = true
    }
    // Most test
kind: ConfigMap
metadata:
  name: alloy-config
