apiVersion: v1
data:
  config.alloy: |-
    // Write your Alloy config here:
    logging {
      level = "info"
      format = "logfmt"
    }
    livedebugging {
      enabled = true
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }
    prometheus.scrape "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [prometheus.remote_write.default.receiver]
    }

    remote.kubernetes.secret "credentials" {
      namespace = {{ .Release.Namespace | quote }}
      name = "grafana-cloud-secret"
    }


    prometheus.remote_write "default" {
      endpoint {
        url = convert.nonsensitive(remote.kubernetes.secret.credentials.data["url"])

        basic_auth {
          username = convert.nonsensitive(remote.kubernetes.secret.credentials.data["username"])
          password = remote.kubernetes.secret.credentials.data["password"]
        }
      }
    }
kind: ConfigMap
metadata:
  name: alloy-config
