resources:
  - namespace.yaml

helmCharts:
- releaseName: internal-ingress-nginx
  name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx 
  valuesInline:
    controller:
      ingressClassResource:
        name: internal-nginx
        controllerValue: k8s.io/internal-ingress-nginx
