apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
      # Role definition : these users are admin
      g, dan@zem.org.uk, role:admin
    # default policy for people logging in --> no privileges, they are blind and can't do anything
  scopes: '[email]'
