resources:
  - namespace.yaml

helmCharts:
- releaseName: ingress-nginx
  name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx 
  valuesInline:
    controller:
      ingressClassResource:
        default: true
