apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pce-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: PCE ({{ .Values.env }}) Project
  destinations:
    - namespace: "pce-{{ .Values.env }}"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://github.com/danfoster/zem-gitops"