apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pce-golinks-{{ .Values.env }}
  namespace: argocd
spec:
  project: pce-{{ .Values.env }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/zemlab/golinks
    targetRevision: main
    path: helm
    helm:
      releaseName: pce-golinks
      valuesObject:
        redirects:
          - from: /map/fort-kinnard
            to: https://portycommunityenergy.wordpress.com/easy-cycle-routes-from-portobello-porty-prom-to-fort-kinnaird
          - from: /map/meadows
            to: https://portycommunityenergy.wordpress.com/easy-cycle-rides-from-portobello-porty-prom-to-the-meadows
          - from: /map/qmu
            to: https://portycommunityenergy.wordpress.com/easy-cycle-rides-from-portobello-porty-prom-to-queen-margaret-university
          - from: /map/leith-links
            to: https://portycommunityenergy.wordpress.com/easy-cycle-rides-to-portobello-porty-prom-to-leith-links

        ingress:
          hostname: go.portycommunityenergy.org
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pce-{{ .Values.env }}
