apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret
    creationPolicy: Owner
  data:
  - secretKey: tunnel-token
    remoteRef:
      key: {{ .Values.externalSecret.remoteRefKey }}
      property: notes
