apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-token
spec:
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: "{{ .Values.externalSecret.remoteRefKey }}"
        property: notes
