apiVersion: v2
name: kubernetes-replicator
description: A Helm chart for kubernetes-replicator on Kubernetes

type: application

version: 0.1.0
appVersion: "2.12.2"

dependencies:
  - name: kubernetes-replicator
    version: 2.12.2
    repository: https://helm.mittwald.de
