{{- range .Values.applications }}
---
# 1. Local Password Generation
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ .name }}-password
spec:
  length: 24
  digits: 5
  symbols: 3
  symbolCharacters: "!#%*"  # MySQL-compatible special characters
  noUpper: false
  allowRepeat: true

---
# 2. Sync to Secret + Reflector Annotation
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-creds-sync
spec:
  refreshInterval: "0"  # Don't regenerate - keep password stable
  target:
    name: mysql-{{ .name }}-creds
    template:
      metadata:
        annotations:
          # This tells Reflector to mirror the secret to the app's home
          replicator.v1.mittwald.de/replicate-to: {{ .namespace | quote }}
      data:
        username: {{ .name }}-user
        password: "{{`{{ .password }}`}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ .name }}-password
      rewrite:
        - regexp:
            source: ".*"
            target: "password"

---
# 3. Create Logical DB, User, and Grant
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ .name }}-db
spec:
  mariaDbRef:
    name: oci-mysql
    kind: ExternalMariaDB
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ .name }}-user
spec:
  mariaDbRef:
    name: oci-mysql
    kind: ExternalMariaDB
  passwordSecretKeyRef:
    name: mysql-{{ .name }}-creds
    key: password
  host: "%"

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ .name }}-grant
spec:
  mariaDbRef:
    name: oci-mysql
    kind: ExternalMariaDB
  privileges: ["ALL PRIVILEGES"]
  database: {{ .name }}-db
  username: {{ .name }}-user
{{- end }}