{{- if .Values.backup.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: {{ .Values.mysql.instanceName }}-backup
spec:
  mariaDbRef:
    name: {{ .Values.mysql.instanceName }}
    kind: ExternalMariaDB
  schedule:
    cron: {{ .Values.backup.schedule | quote }}
    suspend: false
  maxRetention: {{ .Values.backup.maxRetention }}
  storage:
    s3:
      bucket: {{ .Values.backup.b2.bucket }}
      prefix: {{ .Values.backup.b2.prefix }}/{{ .Release.Namespace }}/{{ .Values.mysql.instanceName }}
      endpoint: {{ .Values.backup.b2.endpoint }}
      accessKeyIdSecretKeyRef:
        name: mysql-backup-b2-credentials
        key: ACCESS_KEY_ID
      secretAccessKeySecretKeyRef:
        name: mysql-backup-b2-credentials
        key: SECRET_ACCESS_KEY
{{- end }}
