apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  template:
    metadata:
        app: jellyfin
    spec:
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      containers:
      - name: jellyfin
        volumeMounts:
        - mountPath: /media
          name: media