apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-state-metrics