apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph-external

# Specify base and resources not in base here
resources:
- ../../base/
- pve.cephcluster.yaml
- rook-ceph-mon-endpoints.configmap.yaml
- rook-ceph-mon.secret.yaml
- rook-csi-rbd-node.secret.yaml
- rook-csi-rbd-provisioner.secret.yaml
