apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: clive
spec:
  external:
    enable: true
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
