---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rook-csi-rbd-provisioner
  namespace: rook-ceph-external
spec:
  encryptedData:
    userID: AgCBKUvKN8Y78sCPce5Ix5Ck93n0Z/bilZQ9CMBuaLw28Sck3r+USH7Bk3rLxNW8sEHHV9wevYp1Cjouzkh0Oagyigf7BtZ8KOlPATHKuNXNUDV3pFgRrHlUGvwvCrp3SLPLF8HLrQIUo32rjt+S50SJ3V295XUtHfd0u44iugFbCosYK55DRz/jlNxo1k00FlRsbEhA0uhNZCtgYS7bGdnU6iL4jAZ4jw+AegXpXvV8l4tMJo/XZRDhi9gNwADxBJNbBVNJiiG60R3z8TS5VlMdSd6OTzAW3OueiK8m0R3zj5Pj+Q4w4f5X6UmFOVpCMhy9H1OnMNV/LEqu/MKRYXR0pEeE7WXXLiKwJ81zS4cSNVuzeq0aFdbmfh8qXJnjhN4ueLfjaDhLxf2bSLnc2H5n4PK3bjptL5kr21cRIwyso7LwR0S/5HNDhHO2bJVBBbszsrQqkpYUXJg3m+pMR/ThzyAPJcY6GpAfbAy3wxe3GhGDCe7FKn0Uem6s7/LN8tYxOncWP83DNVRwZzNN3soXG/j56EtiUdn0RtzicZ/oA31j7dEkh/cAPoLfhdP7feNttzSdtR5AJEzZI1hSCDFF26pinvmCVX6sulpabk3YjElORoub+is6Dq57t9ePakeuaz94lyC1ndqfx4rjNzBCybjYV/vbGkTg8iJl2qzhQvY+tVdoPiQKPowOE15NSoyuUs4d4U/fLHcb+1NO32GSI/IP
    userKey: AgAVTgBZ+fo3ZN8PEULnTc+pziOZj44dSgxnhAbhmLoNGpoAHQ0OT8utAYyugAsjZ/PXOr9tTq3jScOeZJEx+tmIg/r6Uy2u+TXTjlGLRPi7a3QJkrAWxmpDbCX8QU+wXYFUMZJRa2ulOEq4FPysUHaYYpLxnOBl3JB53N+bmWFpp2XqAtfWYlxErKCqSEyXiDTu0c3xWLdZDbsomYE3yuVEKiu4mskkzhtyW+gWb+iNcbVk/BhHMgsywaS+cdqUvbekDp4nddYzkGnMDQ5RwTioD7FWLu7W/pDWxPJhX2nqvqDLrRadVltVmiyuliTYG/X5qczXLQH/lSAvQPoxVp0ghGhYfeekZqYnpNdi7kfz6zOk0s9guJXJImGJ9dHP+hMpVA2oTxDqyWWT3QJnIQ2aXz4gPrR1k8ONHLDbWQM840G/LaPstB+j8Ob/z7tY7E+1jxlMlYakZFa/8iP2DJ5md2h039u+joZa05hc6L5eWpe0V2gNTKUJmHBjnQ796rT1eYrg19pxjBBH76IC4xt38e2lBWq5wbRTSRs3AJn2aZjecmmCLqw/YjknXgkp8v97EOGrpRugXeTLy+P0rDutVU1JQTIwXWqT/DhHaBHb/PdeDvtbg5Pw9kTFR1fINdq/aROiw7kjK4M7O6Pl5L+xTS6BswwnZTVynKyfcBF2Qu2MWUg7xc44Bp5rR/n8Gsl0HurXF2xBJMATecxkeK6YHKWm0/sexuGt5v4nccWUFJv71Ici4nWo
  template:
    metadata:
      creationTimestamp: null
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph-external
    type: kubernetes.io/rook
