---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rook-csi-cephfs-provisioner
  namespace: rook-ceph-external
spec:
  encryptedData:
    adminID: AgCYOGMO2vEfjS+zD7r1/ezds312UYX8HSTvbPdMn0937UUDxmPpclWLDFc2wzftrO3j4ZIWNswO5v3+s1flGU1ZT8+8aPWLtGP2GPTQEq94Y5yqncrxTI2iaWxlEZfXZFvMnoP3PBY7g5Vo3mgaqK0CqFSMTJbWlGtBEEx4r2xEN+4l4/J20BYvgecErg/HTRgm9550oSRpgND1V/MLOe25mHOzgRbPyOcBFNOAm8En6H4+EeSfawGBqtQ1f8QSAGmSLbQl8zcKoRIZIByRmpaiR8oTW1qgVgbhCO8JFEt+lWahP6CA4GdzKt7V73RmigW2HdZGSc/w5oziS2IBUOGY0k7wsgj33jRs5jKRxbSQ2kWh2l8YBi0/UHAJHliOQCAiRhl3R0tuMvfPB6gsBcnly5MmdoXvS7xnRDelFewn7qQoC8cZn9JenEJswO/fzPh6Wh7DCpPMDY/yr5HlfBJf8hGKeWhCU/DK0m/mdUhqMOjY4bsXupe7IXyvS235BTkW+LjJPVrLfTNoOdd/YajgjW9VLPtssvUldP1GsVOUz09MAzrZdxNXdCIjFay3d2OxLXAdEF1ffRgqb1B3kA9FayN+5wdRqd0yS/BjrD70MoiomHQpkfBHcUcNNcP6a9c9jBNEKNWPZpB4lmrmxZOx/IMvi/l8zH/xa52NdtKqokxlokqKhj9lDQkJPoEZScoOg42wyuTDvgBn/mqsXC2/CoNjZHhW
    adminKey: AgCRhD5l8C2/1PBloJQhEc0vLwMg/NtSHP5G30qtJJUSKmj8zW3D0LYL2gTvy+8oRzJYwN1vmDGVdnfWtcIaMVc44WNilkDhSQy+kl1+a4tmfns2wVc4UEROP15lwxuBG+ELYnbmjZUi89vLx76B09i56rTBDCWGMHrDSZmJ3svSu/dsWrETkreLbwQgbygCsBrIzDlBlyJCyTIgIGTO2ZgRgJ9bQ1zY5DXEHRyyUDrHHdjrt64NizI6cnFBNccjq2CfW01y182TKwiIIDYa9am247tmry2gk+8+BeF1+aDNUN5g3k+B6c5sgpTGrAW+YB9LLXiANw+B0Ux7hQAC1ESltaEv67uzsgywKQqSwAm+vItFeHbJxJ1mlHQuG79aUY8Vmmk97ct7i0TuxqUtNk7EQzKisMQ6tyPuRrVll58PoCWwy4wjRWwrrINFKY8w2hfZs7ypjRea9GoCHZR/7Se3PvcDvrAk6cCwhU68Ps5UHGPUNfDatwsZ4+4NSu1oF9G88JBi2FbXTxdb+Cl8xswYUa21Y9vU8PC4l2X3Fo7ysMAjDuDMdHVnGjwoNdkw24T1fAOr2FYZDe85qMS8Sg229nNIYMzDKs3ynQZEkdi5a9sQcw19UTBla/BR46JkWuzMfqaDPfbAxEuPY37VnFdiV0uPgj7hxq7SGTS7JjpCqKOcy6eGAHwrQ+mx8jO+uC6NNyijZEs31C/mqer+mVBbKbH4ggHC8LbbSpx27V7ILNNvKYxuLu9+
  template:
    metadata:
      creationTimestamp: null
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph-external
    type: kubernetes.io/rook
