---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rook-csi-cephfs-provisioner
  namespace: rook-ceph-external
spec:
  encryptedData:
    adminID: AgB6xPHHA/1yy0vgjDxGlWq6qIcFqYK5yY5unniomqjLAsidEPOYDxYkCkDx/6rxY5uLU/iaJFByUiUD5fIQrMtnB211dq1B5ZAr2k8rANlajisZoSpcBNJmEfjcLcgmJcXXFF1EAt6T7szD9cWY87b3IrxdSocSXUCbEof9jkgpqWAm3Rgpzcdb56c8dB6rhJ02ukvG9Ryl8ZSFDRSRiCvF4TcaQAEqMJwHY5DjxWmBsIWpM5wg8RYNyG1CbPYx8/S04VGGuy4+CeVNFWQySTpVqPyMfip4bjpjQYe8ir0GQmA/R+XasM6dcd2K2nKg+zTTZkfJbAupSzp1dumGRkO4wWoC6SRRT9Z6ExjHCf7qjus5ZzO0Qt3fn07KOROLrvqdQPgR8pyUl6H1IneVHxgBhS8pVJpHKOlbZHomf603hpzHo9NhO9vh3V7h12MZ/LTrcncDcqzZi2RTiGjzlCj2ocSKaIu4gFff/JamCmUZ17HRgGKWsBCMdoQyacq3odSM0xGAjjoujS4HbmfzZ2kIhM2VWTvsyXdkpRNTBPebHddFLAO3o1HHKEBwM6aj1JVy2uFHwNk+GAvPfiSMYm8SctHq3wE5GvUQ0oJL9BBYB6BbMmrRtm0X4JuMpIHWWaFniwF9om/eeX5YSpkffES4FhpSiLBNn/WyMwA1uSPjKXGyIcJv206kM2oxK1z6MBzFHxyXi887o+JyDW1YmjWrbIwHZPzF
    adminKey: AgB0UO90eepv2ElruAVJR7cEBPU57eRvP4mVab77I3t+SWz/ANaHOqnbfaHrXA5R5mKcySUhnN2XW8QC0U0LyVTDDWFYX1WGOSkzHdFsHMuNkBHofv9SbCm0qB/8L0ULcxGkLqS1ygP76RfFiEcMV8OIWfXeYzZnyOGblWk4c8NKp3ypeyO3hztX7YLSvR18rLkSsdutBV7tro+wK/gUU5Z8i+iz04Uu3HXnkkoIZ9aGSXL198i92UKrYSJBEq9pxTyW87UELSW0vTTRmZb5JZ1g8lydrko2hfBQsgCdNMFnBh6ZsbDD36ofakTNd3HEYoH83h1B5IbcWLwdpUEAiKJVqSlU9EOrgU+scCvMgDOK29ddZ+pEvCYxDW8dDxtJF1olM8xXwiY7/pV+Q9b9QWbL8so9FPNJQhVu0kDtHWjWbvV5OViuldAP2r86KunzdP1wtgZ0Py0v0YAXxrh+fOqw+1+VxMAxwzPXAr43VTrSH+Lotdl/ToWKZW9YSAh0l7S7QfuHO0rWrFNHIifa3RsCtL+5i0neEvqaS0DUUr8ByrLbgH10O0dhjmNmmDwMX0cOFGRk4UWRz3dPq5GgGEpVEcQ8jgwChLC5UMmV5uA6lSTgxsLXIIba6YWQxP8dRoyt1XrRQS7FPDx88YQ4kcUu+rAy4CivZL0kCAI7PQ238UxjjMz5/ZmzFiNaYQro5tixN/47a8XB/+2q8zgHUNOClBtMyTv6E1SUppuNsisrJbX7av92k9eH
  template:
    metadata:
      creationTimestamp: null
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph-external
    type: kubernetes.io/rook
