---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rook-csi-rbd-node
  namespace: rook-ceph-external
spec:
  encryptedData:
    userID: AgBbn1VrK/uRbVnEK76+bDkOlXMlBfMM/GvTaWq3LU5/zvvIn+rzJzh1OwA9P6oMwqwjND+dY1RKsAoG8yyvleYdmfrvV3+jPq/T8dtXVNP3mve4Lw4tP9qfNlf6CJfoQsRz0uj+FpTx0z7BcrnT5i5T+MGmkt5T/VLFEIHytatsMBMXMDePzXOOsJcB5m1pApNwuT/32dc1H/rEN80NiuFlNnWD4Mh8yc6JgQhxKEYDQoJHYoF4+r8QZ4ILoMBqtZxiyU1qqQUC8FoKoCe8jXwgaD0nJ8ntSha91Cg1b5U4HzAXbnV2i9zMt7zXTkW3Z8pggqc6iZAZkb7uaV5PFE5lKYGhkJ/D0geKV+Ju1CEDkIBGV7jf+3iX4SiAhucb43wzmD+OJ7xbA3BtOffoTYzdBafsv1k7gXM3V3aPj7UiQ96+QSYcjRJG/CRcliT598zooQ9R5ASHCL77cE1RwCWMJbY/0xcm67hy1BJCahb1mOEPIJPEwGdwHzp+uVzG/x68J3LHpnB49S04L6BpXvFw3HX/i4XJv5Ndc6cIkWj1zoJH4HC4nIV5S03GKlA+/M0hiH+C8KOYXUbProw5QrrgGA1w8u8lJrer9mmmG8elz/VUci1kxZ80Trr2PUf2p79fo5UG58F1gGqWzmWJqUTBtI1tH+3kLTB0yo2f7EHmMzv/MMhRc3AhHB654zyqoWUsFfs44rwn4KgwgmA=
    userKey: AgBxPoVi8AsgK+iBy+hmr0DZOSgS8noRianE3S2o6zs+FXmQeH1evld/4V81X5eMHGkTPvodUdrG2y3tthjUeExaY0pN1bhGNB1Z+045LzCAl1t6F6itJZA/fPJqjaVud9ScMwyJVVlXJEF0O1LFKvYUraOpHGudd8ILNdntksgK7KcTO5XAUElTpvylY3tBNyZW3k6zWak1tOpY+hI8cZiD4UtROBG63/XfyaMORC4eIBbf+1IvYAOHdsLvQrWtisusnLIYvI01UiZ2OjqVoCKKintqrZqf2ZPpuOI6KD7Ja1iY+Z4CFhqnp7ZBBpuf/EmyA1aD0V/K/bhgBKciOlJXO0i5r8433h1guwTGjXow1IOIpU9yFpuZZL6BI6MDLQTd/mEOM0eUQTXQLUq2FTOQUUYy6/SmS+5NSGD17uzhLUTc4VszcVK6CJ37Ma2Z5G4BjNZ43wPc/mEwOQT+7o7JmHYafBp2srdFGKiAd90UW85ChNxlo8ohb1zIrfyKHNDijF948DbNicKhWB8Id1eFRzlRRfa6YjcnY9mceLCt5iUmL1UPemJKhC88MqBuHwAYlS518Z3UlS6sA9IbT7/Rk2BM1QTH+wpA83lBzDe0RcOQqQOAjwfAdfnQLM7pPlU7rCZbQcFVaF1OONHsQcqJUHcd4QmswVkiRyroKcsxXy58xMPMFZb0jRL1KibwUNAOyBEM5pQsFSTe9Q3G4z7q0Nhvcf7xPF3M44PvfbQGt45tlDsYfDcw
  template:
    metadata:
      creationTimestamp: null
      name: rook-csi-rbd-node
      namespace: rook-ceph-external
    type: kubernetes.io/rook
