---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rook-csi-cephfs-node
  namespace: rook-ceph-external
spec:
  encryptedData:
    adminID: AgBe2t9nynC/RDP+AEC9GnkENJF/Z/PNsYgN5TU3xaG/yWsOz+UHOpQOHCkavvLOvz1ZStkm3Cj+1LQnzGXa4Bo3lPSpH52TOi/wwanDQSYZfej0PDINGA8ALOqMeMIdM9Etx6SqZTwhpxqV8N2MKjZGk5oEWamgG/rovlUj5ZmkoJJo0psjFPMYeogUTvS0I39wNWlqrxqNkyzFIFi7yFcN7Qx9tqZ3DrPVBeAYR3r3oIFODg1cymvpXcVmlPveXmzyHWcq883rspawNvOonv9Tg47ntIhdzmC05s1li7dD8RiqGCHtMezO1CtC/XjgYJMz67m6e2BBTTl/qaJEKnirFuQrS1Sa8cZ4ZDacKZxM2CtXTzu6gb7xPBOj4JOSBmz3+LqA1iqYoK+eFk5ChxcViaAV99y8kaIcCNAn8sMYQflB8eLTNZ8MEXikrF49cid6P8sRCM6Nu9jfYYIcR6FaLpfj9JthsFeKlMq8pchsraBuFi01WdZa5xKC27HcRS1iHXQNZdt9QfQIrJQL2TNal3s0c4AafiAiTxZ0WWuKG3AhAmd4O9mjLtKroQIO1tSuM48h/wwuGc4THamHySOjH6XiuvMiL89rv2LD7xNMoG7XxF6LLkknqFFoA+wBeYlfAYR8cQ/pLsyxGs5iMCYty/sajtDe1YjQJSkNQUqAbbV3CW5g+pVfvscLj1ZeeGu6F89RNBGgMZ19AZG3S8I=
    adminKey: AgCwDMV9lMe5gTkf2PGvjgi3HUaRZX4Zx33YFYU5HDXLgAjA/PHLQl57CVs21lZOQHMwbSajQmk+29ZJs+hcJc6Ic1wy7A6+WLtU58yVwSRTb4o9aqtD29ojQZr6ozQyHpbW7pXacDf5J29N00jhhd4U8nc15m+3A389nCP65GqqvxscoIk0AEua9GSoxU/RSDyb4WhM+k8xQV3vFjsMkoPiCxQLrLXrveCtB0NeaXwk/VYuFRupyyn6thtySfuRT1VV8isborF1h2QKjaiHTvnykPmDIQCcUHhxgt7q7t2P2ooXtRPnRODmhXiJQYZ0eu894MYEulLKhYbuR76XOk2ngTTt5plAnpkVtEY2kKdYPz8Ty57DfWS7hM+gWs1H5PYJ4yW6jzgG6Kdys+I7WlG6BjBlPFb0FmA3kZPWXWZZi9EIwz6IT/qRo//05y8wLRcwEYIkw0w/M+anXDbT26EAokOBU9YuE77NWVGArNLaL9bTM/0jLHrMIUvJiXD4O5TcbjYiYWG0dOvd1QTWp7siNtPFAVu8FtsHSmUJuADbzYMR6mEoth0nKm5+4SFedZef4NRt8LDd2N/8xgx0Cgs+0TTjfolaxShwyD7pTYuNCMKPjh9HuKSV6Z/Wr0un3m9OQ/dIOP/EHY1B9pZoTZeogoY3mTh5S+4vBD0cUEwbh/a9CSkbCFLbNJdBYCE1ByX7c+XHu8xgFg4omJqvSC7EbDpXtYI92qy+8W552QyPPttv6doZgqTv
  template:
    metadata:
      creationTimestamp: null
      name: rook-csi-cephfs-node
      namespace: rook-ceph-external
    type: kubernetes.io/rook
