apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: nfs-csi
  volumeName: photos
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi