apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
spec:
  storageClassName: nfs-csi
  volumeName: photos
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi