immich:
  persistence:
    library:
      existingClaim: photos

  
postgresql:
  enabled: true
  primary:
    resources:
      limits:
        cpu: 150m
        ephemeral-storage: 2Gi
        memory: 512Mi
      requests:
        cpu: 100m
        ephemeral-storage: 50Mi
        memory: 128Mi


redis:
  enabled: true

machine-learning:
  persistence:
    cache:
      type: pvc

server:
  ingress:
    main:
      enabled: true
      annotations:
        # proxy-body-size is set to 0 to remove the body limit on file uploads
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        cert-manager.io/cluster-issuer: "letsencrypt"
        external-dns.alpha.kubernetes.io/target: "209.16.157.32"
      hosts:
        - host: photos.zem.org.uk
          paths: /
      tls:
        - hosts:
            - photos.zem.org.uk
          secretName: photos-tls

