immich:
  persistence:
    library:
      existingClaim: photos

  
postgresql:
  enabled: true
  primary:
    resources:
      limits:
        cpu: 150m
        ephemeral-storage: 2Gi
        memory: 512Mi
      requests:
        cpu: 100m
        ephemeral-storage: 50Mi
        memory: 128Mi


redis:
  enabled: true

machine-learning:
  persistence:
    cache:
      type: pvc