apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zem-external-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/zem-external
    helm:
      valuesObject:
        env: prod
        echo:
          ingress:
            annotations:
              external-dns.alpha.kubernetes.io/target: "137.220.113.26"
          hostname: "echo-c1.zem.org.uk"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
