apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/infra
    helm:
      valuesObject:
        common:
          values:
            cluster:
              name: cluster02
        features:
          metallb:
            enabled: true
          metallb-configs:
            enabled: true
            values:
              addresses:
                - "209.16.157.32/32"
          externaldns:
            enabled: true
            values:
              external-dns:
                txtOwnerId: "zem-c2"
          longhorn:
            enabled: true
            values:
              ingress:
                hostname: longhorn-cluster02
          cloudflared:
            enabled: true
            values:
              externalSecret:
                remoteRefKey: cloudflared-token-cluster02

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
      - /spec/syncPolicy