apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/infra
    helm:
      valuesObject:
        features:
          openebs:
            enabled: true
            storageclasses:
              zfs:
                enabled: true
                poolname: "zroot/openebs"
                default: true
          metallb:
            enabled: true
            addresses:
              - "209.16.157.32/32"
          externaldns:
            enabled: true
            external-dns:
              txtOwnerId: "zem-c2"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
      - /spec/syncPolicy