apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/infra
    helm:
      valuesObject:
        global:
          cluster:
            name: cluster02
        features:
          openebs:
            enabled: true
            storageclasses:
              zfs:
                enabled: true
                poolname: "zroot/openebs"
                default: true
          metallb:
            enabled: true
            addresses:
              - "209.16.157.32/32"
          externaldns:
            enabled: true
            external-dns:
              txtOwnerId: "zem-c2"
          longhorn:
            enabled: true
            ingress:
              hostname: longhorn-cluster02
          cloudflared:
            enabled: true
            cloudflare-tunnel:
              cloudflare:
                account: e858dfdda23dd1f6b72e57841b7a5f52
                tunnelId: 6dafe365-fac3-4610-9f84-bc70b8eb4397
            externalSecret:
              remoteRefKey: clouldflared-token-cluster02

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
      - /spec/syncPolicy