apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
spec:
  project: infra
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress
