apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin-{{ .Values.env }}
  namespace: argocd
spec:
  project: media-{{ .Values.env }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/media/jellyfin
    helm:
      releaseName: jellyfin
      valuesObject:
      {{- toYaml .Values.jellyfin | nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: media-{{ .Values.env }}