apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr-{{ .Values.env }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media-{{ .Values.env }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/media/sonarr
    helm:
      releaseName: sonarr
      valuesObject:
      {{- toYaml .Values.sonarr | nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: media-{{ .Values.env }}