apiVersion: v2
name: zem-homepage
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: "2.1.0"

dependencies:
  - name: homepage
    version: 2.1.0
    repository: https://jameswynn.github.io/helm-charts
