homepage:
  config:
    useExistingConfigMap: homepage
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
  envFrom:
    - secretRef:
        name: homepage-env-secrets
  env:
    LOG_LEVEL: debug
    HOMEPAGE_ALLOWED_HOSTS: "100.64.0.0/10"
