apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  bookmarks.yaml: |
    - Developer:
      - Github:
        - abbr: GH
          href: https://github.com/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Media:
      - Transmission:
          description: Torrent
          href: https://transmission.internal.zem.org.uk
          widget:
            type: transmission
            url: https://transmission.internal.zem.org.uk
            username: zem
            password: {{ HOMEPAGE_VAR_TRANSMISSION_PASSWORD }}
      - Radarr:
          description: Movies
          href: https://radarr.internal.zem.org.uk
  settings.yaml: |
    headerStyle: boxed
    background: https://static.zem.org.uk/images/bg1.jpg
  widgets.yaml: |
    - resources:
        backend: resources
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank

