---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-env-secrets
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_TRANSMISSION_PASSWORD: AgAbGy5r0r8vCgITMEU3WO/6CJKT7YXIScr6CcKSuc+hDV8A8VhRpib+3gr6DJngKXpkrWQIv7soPf7yA1Ql2QVDTE+xzrJSSExIw0H4gwKsmwWIZKjm3Kv21Bqvj59Z3zMrewB7BtnGfNSaGXwlDXdeaL/9LEZIhrJjUewwr/BZ0c5+BeiPrd1VmQyWzrjZVKGtj27cZWTNchSVJHv1wkvlSndesKzcxrEiwQqVqmfZaSyMB9vzSU07tdacx6McZyMdh/2B/aaKcDhIInjqX8SDL6H6Bv5W3fwfL+LyHBVuF8cCEvcNZmbsnLUAtIyRgq8RzCearuEWPcHzq9StadVR1PK1hv5j195QKbd7XhtNMtNxyKMHonYLHjWeBGdZFpzZ7shUckNeausox8UIE93OS2vF5vxLfP7jWRtjObeBSgsLKzIZO7rUoqX1EfqXYIJI2wLqRtuJakXp1rrjqQjTyv1wp1cQwl7ENE6wWwZldLpkkDaIGZhLMxBltkcn9oL0qkv37f3g7SWeeVcs90yrvs8rg/r9qdhMoAWxvcMWV1lps6Q2IRbobQL2zK9FoQSjmTaIKtnc4JkG7rCyjqy63u5qBz95jtNh+ZJTn7Fr5UddQAODhvGNmcDbGBXcyIhPrhoGJgsHtT7+iMgwiYaROHhcmFkbqcdTfauX1NGv6p2t+kF3VoITB7/cvHLvwZQxl+lLuDkbw+KLcKoO
  template:
    metadata:
      creationTimestamp: null
      name: homepage-secrets
      namespace: homepage
    type: Opaque
