kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: echo-prod
  namespace: apps
spec:
  generators:
    - git:
        directories:
          - path: projects/echo/components/*/envs/prod
        repoURL: https://github.com/danfoster/zem-gitops.git
        revision: main
  template:
    metadata:
      name: "{{path[4]}}-{{path.basename}}"
      labels:
        app: echo
    spec:
      destination:
        namespace: "echo"
        server: https://kubernetes.default.svc
      project: "echo"
      source:
        path: "{{path}}"
        repoURL: https://github.com/danfoster/zem-gitops.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true

