apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: echo-prod
  namespace: gitops
spec:
  description: Echo
  destinations:
    - namespace: 'echo-prod'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/danfoster/zem-gitops'
