apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: media
    volumeAttributes:
      collection: default
      replication: "001"
      path: /media
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem