apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  storageClassName: nfs-csi
  volumeName: media
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi