apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  bookmarks.yaml: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Media:
      - Transmission:
          description: Torrent
          href: https://transmission.internal.zem.org.uk
          widget:
            type: transmission
            url: https://transmission.internal.zem.org.uk
            username: zem
            password: {{ HOMEPAGE_VAR_TRANSMISSION_PASSWORD }}
      - Radarr:
          description: Movies
          href: https://radarr.internal.zem.org.uk
          widget:
            type: radarr
            url: https://radarr.internal.zem.org.uk
            key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
  settings.yaml: |
    headerStyle: boxed
    background:
      image: https://static.zem.org.uk/images/bg1.jpg
      blur: xl
      brightness: 23
      opacity: 25
  widgets.yaml: |
    - resources:
        backend: resources
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: google
        target: _blank

