resources:
  - config.yaml
  - secrets.yaml

helmCharts:
- releaseName: homepage
  name: homepage
  repo: https://jameswynn.github.io/helm-charts
  valuesInline:
    config:
      useExistingConfigMap: homepage
    ingress:
      main:
        enabled: true
        ingressClassName: internal-nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
        hosts:
          - host: internal.zem.org.uk
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - internal.zem.org.uk
            secretName: homepage-tls
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    envFrom:
      - secretRef:
          name: homepage-env-secrets
    env:
      LOG_LEVEL: debug