apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  dataSource:
    name: plex-config
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io