kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  serviceName: plex
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      name: plex
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: ghcr.io/linuxserver/plex:1.42.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: '4'
            memory: 2Gi
        ports:
        - containerPort: 32400
          protocol: TCP
        - containerPort: 1900
          protocol: UDP
        - containerPort: 5353
          protocol: UDP
        - containerPort: 8324
          protocol: TCP
        - containerPort: 32410
          protocol: UDP
        - containerPort: 32412
          protocol: UDP
        - containerPort: 32413
          protocol: UDP
        - containerPort: 32414
          protocol: UDP
        - containerPort: 32469
          protocol: TCP


        volumeMounts:
        - mountPath: /data
          name: media
        - mountPath: /config
          name: config

        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/London"
        - name: VERSION
          value: docker

      volumes:
      - name: media
        hostPath:
          path: /data/media
          type: Directory
      - name: config
        persistentVolumeClaim:
          claimName: plex-config