apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plex
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
      containers:
        - image: "mendhak/http-https-echo:31"
          imagePullPolicy: IfNotPresent
          name: echo
          resources:
            limits:
              cpu: '0.1'
              memory: 50Mi
            requests:
              ephemeral-storage: 4Gi
              cpu: '0.1'
              memory: 50Mi
          volumeMounts:
            - mountPath: "/data/media"
              name: media
      restartPolicy: Always
