kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: transmission
    annotations:
        reloader.stakater.com/auto: "true"
    labels:
        app: transmission
spec:
    replicas: 1
    serviceName: transmission
    selector:
        matchLabels:
            app: transmission
    template:
        metadata:
            name: transmission
            labels:
                app: transmission
        spec:
            containers:
            - name: transmission
              image: ghcr.io/linuxserver/transmission:4.0.5
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
                limits:
                  cpu: '1'
                  memory: 1Gi
              ports:
              - containerPort: 9091
                protocol: TCP
              - containerPort: 51413
                protocol: TCP
              - containerPort: 51413
                protocol: UDP

              volumeMounts:
              - mountPath: /downloads
                name: downloads
              - mountPath: /config
                name: config

              env:
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: TZ
                value: "Europe/London"
              - name: USER
                valueFrom:
                  secretKeyRef:
                    name: transmission-user
                    key: username
              - name: PASS
                valueFrom:
                  secretKeyRef:
                    name: transmission-user
                    key: password

            volumes:
            - name: downloads
              persistentVolumeClaim:
                claimName: downloads
            - name: config
              persistentVolumeClaim:
                claimName: transmission-config