apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  storageClassName: nfs-csi
  volumeName: downloads
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi