---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-user
  namespace: media-prod
spec:
  encryptedData:
    password: AgBLQ3Oto7d+KcuewsgnSR/H/380iysFtjm+j+Edx2KcotscX5O75vq4je2jdztvoyyqkja4JbujnOzzjJ0Shsztg8240IrP1Vv4CFog3rcRyRXu+Jf+8+w4EZzh691w4l+J4JxK3Oq1CLo775WB14nVTQ7JUKgOfxjWh1jr+ApdMksSaT4tl/qnxEd2Y9jwJwG0RwLolSIXGGnDrEqr0CAIAAmKBGvynjPE4lmFEpBmKAmIrmf5YYxiOd3jeqSZ5OTnrEJxoCGnmbX6YXuxQf/O7OABmx682SluhR6HVDoafuN3d/1hDyp/2AYI1c/s7nKPH6JPN8H7MNwpmSgcX+nKoF2jvaZ0uJsOnYdyxSM3cDdX5kNyMiOoACg/r4yMnFI1NKzOYinnjCYn/MOEPtF5qEL7QJ6bWvYBdZVcMthEqZUPyTPKb9tP12AMH9zYIbrurPlPFfZbnVPS+kbDueSTRLNqjmuEmvvMN5kFpj35hpL6ZxCs9RovWUF+ttwfK49AXo6xLjqSsh+2qPs5N8v+aludBtGsmX+I9wx3W5Sq/QYHDwco3y2nfP6E8Y+czqiQCZU4LujRgkW1Sqc+t+G0WbFpx+lS+SVJzs7B196h3IkIXKZnDfQfjLvG4nvajXEa7waT3OcJKgb4ufrsLxaOq6WanW8bsTsJPProOb5sdUJsGIf9oYFqkSnDyZiOV2sKFb1SIOsGBgEMmDk=
    username: AgCWzkKviqQMInAf1sbnvhqLU5LvJXN21pgsFaCr82M4InnNp7bRFxxqm5U0UAFQQHQNSZ/lMsorMLtAM+U3YBOWqd8HgSUYB8BMzhwt/rSzRO1xXhqj3t2q5WIGsrPOYhfQSo6+CfN8/JxYlOnUKGF7OKtCeexBEZVTj6ruwlnCj25bGSN3M1yoal5YLsZoUC8kFKFH08+PnXU/ZLBrBW3nnDP05aoX6OC25mwVJsLH74qxpinKweJkox+Pforpcimff+sXjoqYixTIr6t3UfSwdysj1Eweg9sP/F+kaRaWRMVf5bBPjwB7NjaIL7HqevlfSScGqV7skL+LVbDxSr4wzRsUbkze8oJ5szxGGTtcD2i3ePz5zoUfAL65vNOaX2iSrBZMd00B298dMbPmQs00UHEZPd3UfVMF01OXskClMyFZm3+TwcCL3qkVBmjJzqQSl5uCq5MFGb1AXa52L08glSaJp9H4Vpyg/4Tk+nvjN+NL7qrYw1RhDDwF4Wz4A5CupwRgpkQXdsHQUi1f/6vNj/bLrucUhtXfYyIsqJEiGdURF2TlgQtKD/OyHYpaKJHD2lWVN0nGnPFU5jzmzN4o1UJMEYdCk/WDj1MUmtm5WgnY0ZP7CPxiq+3BZ89TKYFUboEFrwb6GoUm7NTGwNd0rkondH/Y1FFp5BE6/HHYBztFojqrH6X4sDUdoki+8gjLy0Q=
  template:
    metadata:
      creationTimestamp: null
      name: transmission-user
      namespace: media-prod
    type: Opaque
