apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - cluster01-argocd
  defaultBackend:
    service:
      name: argocd-server
      port:
        number: 80
