apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zem-github-creds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        githubAppID: "868367"
        githubAppInstallationID: "49174761"
        githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
        type: git
        url: https://github.com/danfoster
  data:
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: "argo-github-app-private-key"
