apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pce-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/pce
    helm:
      valuesObject:
        env: prod
        cluster: cluster03
        ociVault:
          vaultOcid: "ocid1.vault.oc1.uk-london-1.eruxsrmlaafja.abwgiljridwbzbxrs2vvay6b6n6x7xhi3ymapbgov36lrqmm7bkxgh3hmnka"
          compartmentOcid: "ocid1.compartment.oc1..aaaaaaaagyawjldswlrq2f2dnsqz2kqlzsvj6mirpcue7oqwzlyuwx7pqjha"
          region: "uk-london-1"
          tenancyOcid: ""
        backups:
          ociUserOcid: ""
          ociCredentialSecret: "pce-prod-oci-creds"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
