apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-{{ .Values.env }}
  namespace: argocd
spec:
  project: zem-internal-{{ .Values.env }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 9.2.9
    helm:
      releaseName: grafana
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: tailscale
          tls:
            - hosts:
                - grafana
          hosts:
            - grafana

  destination:
    server: "https://kubernetes.default.svc"
    namespace: zem-internal-{{ .Values.env }}
