apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proxmox-csi

resources:
  - ../../base/

helmCharts:
  - releaseName: proxmox-csi-plugin
    name: proxmox-csi-plugin
    namespace: proxmox-csi
    repo: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    valuesInline:
      # proxmox-csi.yaml
      config:
        clusters:
          - url: https://10.43.0.251:8006/api2/json
            insecure: false
            token_id: "kubernetes-csi@pve!csi"
            token_secret: "secret"
            region: Region-1
          # Add more clusters if needed
          - url: https://cluster-api-2.exmple.com:8006/api2/json
            insecure: false
            token_id: "kubernetes-csi@pve!csi"
            token_secret: "secret"
            region: Region-2

      # Define the storage classes
      storageClass:
        - name: proxmox-data-xfs
          storage: data
          reclaimPolicy: Delete
          fstype: xfs
