apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin
# Specify base and resources not in base here
resources:
- ../../base/
- media.pv.yaml

patches:
  - path: patches/deployment.yaml