env: prod
cluster: ""
wordpress:
  db:
    host: "10.44.0.209"
    name: "pce-prod-db"
    userSecretRef:
      name: mysql-pce-prod-creds
ociVault:
  vaultOcid: ""
  compartmentOcid: ""
  region: "uk-london-1"
  tenancyOcid: ""
backups:
  ociUserOcid: ""
  ociCredentialSecret: ""
