apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops
  namespace: argocd
spec:
  description: GitOps Project
  destinations:
    - namespace: 'gitops'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/danfoster/zem-gitops'
