apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: transmission
      port:
        number: 9091
  tls:
  - hosts:
    - transmission
