kind: Service
apiVersion: v1
metadata:
    name: transmission
    {{- if .Values.service.annotations }}
    annotations:
      {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
    type: LoadBalancer
    selector:
        app: transmission
    ports:
    - protocol: TCP
      name: web-interface
      port: 9091
    - protocol: TCP
      name: torrent-tcp
      port: 51413
    - protocol: UDP
      name: torrents-udp
      port: 51413