apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: transmission-user
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        username: "zem"
        password: "{{ `{{.password}}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: "transmission-web-password"
