apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: GitOps Project
  destinations:
    - namespace: 'apps'
      server: 'https://kubernetes.default.svc'
    - namespace: 'echo'
      server: 'https://kubernetes.default.svc'
    - namespace: 'omada'
      server: 'https://kubernetes.default.svc'
    - namespace: 'jellyfin'
      server: 'https://kubernetes.default.svc'
    - namespace: 'torrent'
      server: 'https://kubernetes.default.svc'
    - namespace: 'homepage'
      server: 'https://kubernetes.default.svc'    
    - namespace: 'radarr'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/danfoster/zem-gitops'
