apiVersion: v2
name: zem-tailscale
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.84.0"

dependencies:
  - name: tailscale-operator
    version: 1.84.0
    repository: https://pkgs.tailscale.com/helmcharts
