apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  bookmarks.yaml: |
    - Developer:
      - Github:
          - abbr: GH
            href: https://github.com/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Media:
      - Plex:
          description: Plex Media Server
          href: https://plex.zem.org.uk
          widget:
            type: plex
            url: http://plex.media-prod:32400
            key: {{ `{{HOMEPAGE_VAR_PLEX_API_KEY}}` }}
      - Transmission:
          description: Torrent
          href: https://transmission.shark-puffin.ts.net
          widget:
            type: transmission
            url: http://transmission.media-prod:9091
            username: zem
            password: {{ `{{HOMEPAGE_VAR_TRANSMISSION_PASSWORD}}` }}
      - Radarr:
          description: Movies
          href: https://radarr.shark-puffin.ts.net
          widget:
            type: radarr
            url: http://radarr.media-prod:7878
            key: {{ `{{HOMEPAGE_VAR_RADARR_API_KEY}}` }}
      - Sonarr:
          description: TV
          href: https://sonarr.shark-puffin.ts.net/sonarr
          widget:
            type: sonarr
            url: http://sonarr.media-prod:8989
            key: {{ `{{HOMEPAGE_VAR_SONARR_API_KEY}}` }}
    - Networking:
      - Omada:
          description: Wireless Controller
          href: https://10.42.2.202:8043/
          widget:
            type: omada
            url: https://10.42.2.202:8043/
            username: zem
            password: noused
            site: zem
    - Home Automation:
      - Home Assistant:
          href: http://10.42.2.200:8123/lovelace/0
          widget:
            type: homeassistant
            url: http://10.42.2.200:8123/
            key: {{ `{{HOMEPAGE_VAR_HA_API_TOKEN}}` }}
    - Infrastructure:
      - Grafana:
          href: https://zemlab.grafana.net/a/cloud-home-app
      - Tailscale Admin:
          href: https://login.tailscale.com/admin/machines
      - Cluster 01 ArgoCD:
          href: https://argocd-cluster01.shark-puffin.ts.net
          description: Home
          widget:
            type: argocd
            url: http://argocd-server.argocd
            key: {{ `{{HOMEPAGE_VAR_ARGOCD_CLUSTER01_API_KEY}}` }}
      - Cluster 02 ArgoCD:
          href: https://argocd-cluster02.shark-puffin.ts.net
          description: Hacklab
          widget:
            type: argocd
            url: http://argocd-server.argocd
            key: {{ `{{HOMEPAGE_VAR_ARGOCD_CLUSTER02_API_KEY}}` }}
      - Bitwarden Secrets Manager:
          href: https://vault.bitwarden.com/#/sm/601c33f4-f861-4d10-bca3-b0a9008c7752
      - Oracle Cloud:
          href: https://cloud.oracle.com/?region=uk-london-1

  settings.yaml: |
    headerStyle: boxed
  widgets.yaml: |
    - resources:
        backend: resources
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: google
        target: _blank
