apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-env-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  data:
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: "test"
    - secretKey: HOMEPAGE_VAR_ROUTER02_API
      remoteRef:
        key: "test"
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: "test"
    - secretKey: HOMEPAGE_VAR_TRANSMISSION_PASSWORD
      remoteRef:
        key: "transmission-web-password"
    - secretKey: HOMEPAGE_VAR_ARGOCD_CLUSTER01_API_KEY
      remoteRef:
        key: "argocd-cluster01-api-key"
    - secretKey: HOMEPAGE_VAR_PLEX_API_KEY
      remoteRef:
        key: "plex-api-token"
