apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-env-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  data: []