apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: zem-internal-prod
  namespace: argocd
spec:
  description: zem-internal
  destinations:
    - namespace: 'zem-internal-prod'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/danfoster/zem-gitops'
