apiVersion: v2
name: zem-argocd
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: "3.0.5"

dependencies:
  - name: argo-cd
    version: 8.0.14
    repository: https://argoproj.github.io/argo-helm
