kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: projects-cluster02
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: clusters/cluster02/projects/*
        repoURL: https://github.com/danfoster/zem-gitops.git
        revision: main
  template:
    metadata:
      name: "{{path.basename}}"
      labels:
        cat: projects
    spec:
      destination:
        namespace: "argocd"
        server: https://kubernetes.default.svc
      project: "gitops"
      source:
        path: "{{path}}"
        repoURL: https://github.com/danfoster/zem-gitops.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true

