apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/infra
    helm:
      valuesObject:
        common:
          values:
            cluster:
              name: cluster03
        features:
          externaldns:
            enabled: true
            values:
              external-dns:
                txtOwnerId: "zem-c3"
          ingress-nginx:
            enabled: true
            values:
              controller:
                service:
                  annotations:
                    oci.oraclecloud.com/load-balancer-type: "nlb"
          longhorn:
            enabled: true
            values:
              ingress:
                hostname: longhorn-cluster03
          cloudflared:
            enabled: true
            values:
              externalSecret:
                remoteRefKey: cloudflared-token-cluster03
          mariadb-operator:
            enabled: true
          kubernetes-replicator:
            enabled: true
          oci-mysql:
            enabled: true
            namespace: oci-mysql
            source:
              repoURL: https://github.com/danfoster/zem-gitops
              targetRevision: main
              path: apps/infra/zem-external-dbs
            values:
              oci:
                vaultOcid: ocid1.vault.oc1.uk-london-1.eruxsrmlaafja.abwgiljridwbzbxrs2vvay6b6n6x7xhi3ymapbgov36lrqmm7bkxgh3hmnka
                compartmentOcid: ocid1.compartment.oc1..aaaaaaaagyawjldswlrq2f2dnsqz2kqlzsvj6mirpcue7oqwzlyuwx7pqjha
                # rootSecretOcid: ocid1.key.oc1.uk-london-1.eruxsrmlaafja.abwgiljtncunmpibvwvjygia2d3umhb6vf24axjuxuivbg52moq76tgdhdua
                rootSecretOcid: mysql-admin-password
              mysql:
                host: "10.44.0.209"
              applications:
                - name: "pce-prod"
                  namespace: "pce-prod"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
      - /spec/syncPolicy