apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/infra
    helm:
      valuesObject:
        global:
          values:
            cluster:
              name: cluster03
        features:
          externaldns:
            enabled: true
            values:
              external-dns:
                txtOwnerId: "zem-c3"
          ingress-nginx:
            enabled: true
            values:
              controller:
                service:
                  annotations:
                    oci.oraclecloud.com/load-balancer-type: "nlb"
          longhorn:
            enabled: true
            values:
              ingress:
                hostname: longhorn-cluster03
          cloudflared:
            enabled: true
            values:
              externalSecret:
                remoteRefKey: clouldflared-token-cluster03
          mariadb:
            enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
      - /spec/syncPolicy