apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/infra
    helm:
      valuesObject:
        features:
          openebs:
            enabled: true
            storageclasses:
              zfs:
                enabled: true
                poolname: "zroot/openebs"
                default: true
          metallb:
            enabled: true
            addresses:
              - 10.42.2.201-10.42.2.220
          externaldns:
            enabled: true
            external-dns:
              txtOwnerId: "zem-c1"
          vmagent:
            enabled: true
          zfs_exporter:
            enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
