apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/infra
    helm:
      valuesObject:
        features:
          argocd:
            enabled: true
            globals:
              domain: argocd-cluster01.shark-puffin.ts.net
          externalsecrets:
            enabled: true
          openebs:
            enabled: true
            storageclasses:
              zfs:
                enabled: true
                poolname: "zroot/openebs"
                default: true
          tailscale:
            enabled: true
            tailscale-operator:
              operatorConfig:
                hostname: "cluster01"
                defaultTags:
                  - "tag:cluster01-operator"
              proxyConfig:
                defaultTags: "tag:cluster01"
            oauth:
              clientId: "kkb7j1384C11CNTRL"
              clientSecretKey: "tailscale-cluster01-client-secret"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
