apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/infra
    helm:
      valuesObject:
        global:
          values:
            cluster:
              name: cluster01
        features:
          openebs:
            enabled: true
          metallb:
            enabled: true
          metallb-configs:
            enabled: true
            values:
              addresses:
                - 10.42.2.210-10.42.2.220
          externaldns:
            enabled: true
            values:
              external-dns:
                txtOwnerId: "zem-c1"
          smartctl-exporter:
            enabled: true
          longhorn:
            enabled: true
            values:
              ingress:
                hostname: longhorn-cluster01

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
      - /spec/syncPolicy