apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.c2.internal.zem.org.uk
  kustomize.buildOptions: --enable-helm
  dex.config: |
    connectors:
    - config:
        issuer: https://accounts.google.com
        clientID: 414171075394-bn6ugphd1h7qra7qp15vs9qr9ogn8tpp.apps.googleusercontent.com
        clientSecret: $google-oauth:client_secret
        redirectURI: https://argocd.c2.internal.zem.org.uk/api/dex/callback
      type: oidc
      id: google
      name: Google

