apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-oauth
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  data:
    - secretKey: client_secret
      remoteRef:
        key: "argo-google-oauth-client-secret"
