---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAPkaFZwvq81Qc/zRkdGqErj6lE2a29owzBqAjyHHxYzLfREY54ZspO085WJu1Mj6I5d1ITLVDI/j/OLs1R/ByIvjMKqfzj05bXFB+N96y3Az7NASdxoq7GjLY6ZmsXBOu1sFFnnV6hks7qPJwz4g7ekOpRi/99ehA2FiIuHSsZ1UE1x4pfTmvjUksh6Xs6yooojShCvlqHrbSKJdvnd+WLq1XqRVf3Awt5nPZUuxzeLoWbZTHclB4MSVcGhmmdVwqPMea4pzD8z+bywm+UwgcNMoJFl5GJTiTP/gMuZJbTWtuwQShoCYAspFhGseYmVwaCPSErl69JDwBYwaWwhoz97Il+RStl+A9iccKIy9GpshaNftGQ5U2HB9tJgBWfKG7kt5Nkz8E9axBYf9JBbVeavojvTrndZu8su81t90axAjOTLDOlTh9Pd2oH3n84rZ6qB5AjbCaEe9jTByUnsa0wznzU7G3EuxXid4mMTOMfRg602HL3ShU7m6RGiXDlm6cTd4wNTAn5UATnnPgB5mm5jVGN9TpNKjtYY3HBzRok8CRG1NR60HBUa8FxD/RRgh5Z0vHHSlk137wB/4y+J5qSFo6ixPMZ9hAOsu9mNDIFtTJOzW8yA9pWl5sk2CBs4iZWgbaMBr+HqQCK+RNOXIEex6LMzl6gzUfCURkl63ENQlGUFedILQqosTpXiSxUWXiolDVvh1gH80HAp4UdxQqm3w==
    client_secret: AgBsCGzBDBbRIC0JQtTGrhHs0U8Yz2FtO1J6VVEL+UfSn55J6cBTpZRKUqwU4ZSOTTw6rZIPGZztPrV51aWTiD+2ddW3+MxxJLSNwS6dOAfJZq1shKJmHrbS3VVJp0pgNwy0uoUF7Auj30ErfD+882il/qtaENNkDm/qm9STnxcmlGD9VFdxQNPIcMOgRTzq47bpzV2OQRLMpzxpWTFe1YBYA7V0iGxqmtZQLhTjnTjtbaB45xiqS9Sff2e92kTH8ED+UcKcWVKxVPstEwjuMZYlT04O60TRWS+v+ePItyoVeQ36J7B2npxOw8egbRH4dJrrRl/urmnle0drGlr+OZoJUIuqyjdsMBoBChvs5kxd0+89xaBCZH5f6IH+vUDi3UZreLj/Z7dsBF91x6B+FiHtO1UousXmk9CCsynDsoPUYFbG2pUHJ2benPU5pds5ZfH1tHXQ4/zwMETg48m3XHXLhRMbx1nDvghw6VErxHV632n23hjvsiLR/DB+U6Zvi+JvQ5JLlO8njgQirTZESNQzt19CAalF088rE5s3dCItMRprh749TU79KVLj7acIoGSfD3fYoXikAGjcCwKeIhHJtZmTXj06NazEyvdQH6DHQeOkb49t54ulEhTXbPMY4qhMYiW6QP9Vc0CudIWwsZ9wztp3dXYjglqNY1gnOSmTYJ9/Mol/j4fPLgAWT7f6i/rk/C+yt3RyP5H9LFax0B4UJaMdmDq61owEA9+IMQJCjQ3B89OdFMxiBO+OUNc2NcDivIO3Yq45cJ46nNm6r/ts
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
