kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: zem-collab-prod
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: projects/zem-collab/apps/*/envs/prod
        repoURL: https://github.com/danfoster/zem-gitops.git
        revision: main
  template:
    metadata:
      name: "{{path[1]}}-{{path[3]}}-{{path.basename}}"
      labels:
        app: zem-collab
    spec:
      destination:
        namespace: "{{path[1]}}-{{path.basename}}"
        server: https://kubernetes.default.svc
      project: "{{path[1]}}-{{path.basename}}"
      source:
        path: "{{path}}"
        repoURL: https://github.com/danfoster/zem-gitops.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true

