apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: GitOps Project
  destinations:
    - namespace: "argocd"
      server: "https://kubernetes.default.svc"
    - namespace: "gitops"
      server: "https://kubernetes.default.svc"
    - namespace: "kube-system"
      server: "https://kubernetes.default.svc"
    - namespace: "cert-manager"
      server: "https://kubernetes.default.svc"
    - namespace: "metallb-system"
      server: "https://kubernetes.default.svc"
    - namespace: "ingress"
      server: "https://kubernetes.default.svc"
    - namespace: "ingress-internal"
      server: "https://kubernetes.default.svc"
    - namespace: "tailscale"
      server: "https://kubernetes.default.svc"
    - namespace: "externaldns"
      server: "https://kubernetes.default.svc"
    - namespace: "default"
      server: "https://kubernetes.default.svc"
    - namespace: "rook-ceph-operator"
      server: "https://kubernetes.default.svc"
    - namespace: "rook-ceph-external"
      server: "https://kubernetes.default.svc"
    - namespace: "rook-ceph"
      server: "https://kubernetes.default.svc"
    - namespace: "nfs-csi"
      server: "https://kubernetes.default.svc"
    - namespace: "reloader"
      server: "https://kubernetes.default.svc"
    - namespace: "postgres-operator"
      server: "https://kubernetes.default.svc"
    - namespace: "external-secrets"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://github.com/danfoster/zem-gitops"
