apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
        - image: "docker.io/dokuwiki/dokuwiki:2025-05-14b"
          imagePullPolicy: IfNotPresent
          name: wiki
          env:
            - name: PHP_TIMEZONE
              value: "Europe/London"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "500m"
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wiki-data
