apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.hostname | quote }}
      secretName: ingress-wiki-tls
  rules:
    - host: {{ .Values.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wiki
                port:
                  number: 8000
