kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wiki-data
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
