apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: GitOps Project
  destinations:
    - namespace: "argocd"
      server: "https://kubernetes.default.svc"
    - namespace: "cert-manager"
      server: "https://kubernetes.default.svc"
    - namespace: "ingress"
      server: "https://kubernetes.default.svc"
    - namespace: "tailscale"
      server: "https://kubernetes.default.svc"
    - namespace: "externaldns"
      server: "https://kubernetes.default.svc"
    - namespace: "reloader"
      server: "https://kubernetes.default.svc"
    - namespace: "postgres-operator"
      server: "https://kubernetes.default.svc"
    - namespace: "openebs"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://github.com/danfoster/zem-gitops"
