apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: cadvisor-metrics
spec:
  # The path for cAdvisor metrics
  path: /metrics/cadvisor
  # Kubelet metrics are usually served over HTTPS
  scheme: https
  interval: 30s
  scrapeTimeout: 10s
  tlsConfig:
    # Most Kubelet certs are self-signed by the K8s CA
    insecureSkipVerify: true
  # Authentication is required for the Kubelet
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabelConfigs:
    # Standard relabeling to make labels like 'node' readable
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - targetLabel: job
      replacement: cadvisor
  metricRelabelConfigs:
    # 1. Drop any metric that doesn't have a container name (usually junk/summary metrics)
    - sourceLabels: [container]
      regex: "^$"
      action: drop
    # 2. Drop "POD" containers (the pause container) to save space
    - sourceLabels: [container]
      regex: "POD"
      action: drop
    # This regex drops common OCI infrastructure noise labels
    # while keeping standard ones like 'node' or 'instance'
    - action: labeldrop
      regex: "(beta_kubernetes_io_.*|failure_domain_.*|node_info_.*|oci_oraclecloud_com_.*|oke_oraclecloud_com_.*|topology_kubernetes_io_.*)"
