apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: node-exporter
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-exporter